CPPFLAGS :=
	-I../opencv-1/modules/objdetect/include \
	-I../opencv-1/modules/highgui/include \
	-I../opencv-1/modules/imgproc/include \
	-I../opencv-1/modules/core/include \
	-I../opencv-1/modules/imgcodecs/include \
	-I../opencv-1/modules/videoio/include

LDFLAGS :=
	-L../opencv-1/debug/lib

LDLIBS :=
	-lopencv_core -lopencv_videoio -lopencv_highgui \
	-lopencv_imgproc -lopencv_video -lopencv_objdetect

$(CXX) $(INCPATH) $(LIBPATH) $^ $(LIBS) -o $@
